# Generated by Django 3.2 on 2021-04-15 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0003_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
