# Generated by Django 3.2 on 2021-04-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0005_contactusform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactusForm',
        ),
    ]
