# Generated by Django 3.2 on 2021-05-04 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0007_blogpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blogpost',
            new_name='blog_post',
        ),
    ]
