# Generated by Django 3.2 on 2021-05-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0009_auto_20210506_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connectus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('mname', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('address', models.TextField(max_length=150)),
                ('mobile', models.IntegerField(max_length=10)),
                ('subject', models.TextField(max_length=150)),
                ('message', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
