# Generated by Django 3.2 on 2021-05-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0010_auto_20210508_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('updated',)},
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogimages',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
