# Generated by Django 3.2 on 2021-05-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0011_auto_20210510_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='blogimages',
            new_name='blogimage',
        ),
    ]
