# Generated by Django 3.2.4 on 2021-06-25 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0012_rename_blogimages_blogpost_blogimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ('-updated',)},
        ),
    ]
