# Generated by Django 3.2.4 on 2021-06-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0013_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectus',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
