# Generated by Django 3.2.4 on 2021-06-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0014_alter_connectus_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogimage',
            field=models.ImageField(blank=True, upload_to='image/blogimage'),
        ),
    ]
