# Generated by Django 3.2.4 on 2021-06-25 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0015_alter_blogpost_blogimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
