# Generated by Django 3.2.4 on 2021-06-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0016_alter_blogpost_blog_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='blogimage',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogpostimage',
            field=models.ImageField(blank=True, upload_to='blogpostimage/'),
        ),
    ]
