# Generated by Django 3.2.4 on 2021-06-27 04:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0017_auto_20210625_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_post',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
