# Generated by Django 3.2.4 on 2021-06-27 08:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0019_alter_blogpost_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_post',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
