# Generated by Django 3.2.4 on 2021-06-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywebsite', '0020_alter_blogpost_blog_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blogpostimage',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
